import { z } from 'zod';
import { MessageType, ReactionEmoji, Gender } from './enums';
export declare const SendOtpSchema: z.ZodObject<any>;
export declare const VerifyOtpSchema: z.ZodObject<any>;
export declare const RefreshTokenSchema: z.ZodObject<any>;
export declare const CreateUserSchema: z.ZodObject<any>;
export declare const UpdateUserSchema: z.ZodObject<any>;
export declare const UpdateProfileSchema: z.ZodObject<any>;
export declare const UpdateAdminProfileSchema: z.ZodObject<any>;
export declare const SendMessageSchema: z.ZodObject<any>;
export declare const EditMessageSchema: z.ZodObject<any>;
export declare const CreateNewsletterPostSchema: z.ZodObject<any>;
export declare const UpdateNewsletterPostSchema: z.ZodObject<any>;
export declare const ReactToPostSchema: z.ZodObject<any>;
export declare const CursorPaginationSchema: z.ZodObject<any>;
export declare const PagePaginationSchema: z.ZodObject<any>;
export type SendOtpInput = z.infer<typeof SendOtpSchema>;
export type VerifyOtpInput = z.infer<typeof VerifyOtpSchema>;
export type CreateUserInput = z.infer<typeof CreateUserSchema>;
export type UpdateUserInput = z.infer<typeof UpdateUserSchema>;
export type UpdateProfileInput = z.infer<typeof UpdateProfileSchema>;
export type UpdateAdminProfileInput = z.infer<typeof UpdateAdminProfileSchema>;
export type SendMessageInput = z.infer<typeof SendMessageSchema>;
export type EditMessageInput = z.infer<typeof EditMessageSchema>;
export type CreateNewsletterPostInput = z.infer<typeof CreateNewsletterPostSchema>;
export type UpdateNewsletterPostInput = z.infer<typeof UpdateNewsletterPostSchema>;
export type ReactToPostInput = z.infer<typeof ReactToPostSchema>;
