export const provinces = [
  { label: "آذربایجان شرقی", value: "آذربایجان شرقی" },
  { label: "آذربایجان غربی", value: "آذربایجان غربی" },
  { label: "اردبیل", value: "اردبیل" },
  { label: "اصفهان", value: "اصفهان" },
  { label: "البرز", value: "البرز" },
  { label: "ایلام", value: "ایلام" },
  { label: "بوشهر", value: "بوشهر" },
  { label: "تهران", value: "تهران" },
  { label: "چهارمحال و بختیاری", value: "چهارمحال و بختیاری" },
  { label: "خراسان جنوبی", value: "خراسان جنوبی" },
  { label: "خراسان رضوی", value: "خراسان رضوی" },
  { label: "خراسان شمالی", value: "خراسان شمالی" },
  { label: "خوزستان", value: "خوزستان" },
  { label: "زنجان", value: "زنجان" },
  { label: "سمنان", value: "سمنان" },
  { label: "سیستان و بلوچستان", value: "سیستان و بلوچستان" },
  { label: "فارس", value: "فارس" },
  { label: "قزوین", value: "قزوین" },
  { label: "قم", value: "قم" },
  { label: "کردستان", value: "کردستان" },
  { label: "کرمان", value: "کرمان" },
  { label: "کرمانشاه", value: "کرمانشاه" },
  { label: "کهگیلویه و بویراحمد", value: "کهگیلویه و بویراحمد" },
  { label: "گلستان", value: "گلستان" },
  { label: "گیلان", value: "گیلان" },
  { label: "لرستان", value: "لرستان" },
  { label: "مازندران", value: "مازندران" },
  { label: "مرکزی", value: "مرکزی" },
  { label: "هرمزگان", value: "هرمزگان" },
  { label: "همدان", value: "همدان" },
  { label: "یزد", value: "یزد" },
];

export const citiesByProvince: Record<string, Array<{ label: string; value: string }>> = {
  "آذربایجان شرقی": [
    { label: "تبریز", value: "تبریز" },
    { label: "مراغه", value: "مراغه" },
    { label: "میانه", value: "میانه" },
    { label: "شبستر", value: "شبستر" },
    { label: "اهر", value: "اهر" },
    { label: "بناب", value: "بناب" },
    { label: "سراب", value: "سراب" },
    { label: "ملکان", value: "ملکان" },
    { label: "آذرشهر", value: "آذرشهر" },
    { label: "هشترود", value: "هشترود" },
  ],
  "آذربایجان غربی": [
    { label: "ارومیه", value: "ارومیه" },
    { label: "خوی", value: "خوی" },
    { label: "بوکان", value: "بوکان" },
    { label: "مهاباد", value: "مهاباد" },
    { label: "سلماس", value: "سلماس" },
    { label: "میاندوآب", value: "میاندوآب" },
    { label: "نقده", value: "نقده" },
  ],
  "اردبیل": [
    { label: "اردبیل", value: "اردبیل" },
    { label: "پارس آباد", value: "پارس آباد" },
    { label: "خلخال", value: "خلخال" },
    { label: "مشگین شهر", value: "مشگین شهر" },
    { label: "گرمی", value: "گرمی" },
  ],
  "اصفهان": [
    { label: "اصفهان", value: "اصفهان" },
    { label: "کاشان", value: "کاشان" },
    { label: "نجف آباد", value: "نجف آباد" },
    { label: "خمینی شهر", value: "خمینی شهر" },
    { label: "شاهین شهر", value: "شاهین شهر" },
    { label: "فلاورجان", value: "فلاورجان" },
    { label: "نطنز", value: "نطنز" },
    { label: "گلپایگان", value: "گلپایگان" },
  ],
  "البرز": [
    { label: "کرج", value: "کرج" },
    { label: "نظرآباد", value: "نظرآباد" },
    { label: "فردیس", value: "فردیس" },
    { label: "ساوجبلاغ", value: "ساوجبلاغ" },
    { label: "طالقان", value: "طالقان" },
  ],
  "ایلام": [
    { label: "ایلام", value: "ایلام" },
    { label: "دهلران", value: "دهلران" },
    { label: "دره شهر", value: "دره شهر" },
    { label: "آبدانان", value: "آبدانان" },
  ],
  "بوشهر": [
    { label: "بوشهر", value: "بوشهر" },
    { label: "برازجان", value: "برازجان" },
    { label: "کنگان", value: "کنگان" },
    { label: "گناوه", value: "گناوه" },
  ],
  "تهران": [
    { label: "تهران", value: "تهران" },
    { label: "ری", value: "ری" },
    { label: "ورامین", value: "ورامین" },
    { label: "اسلامشهر", value: "اسلامشهر" },
    { label: "پاکدشت", value: "پاکدشت" },
    { label: "شهریار", value: "شهریار" },
    { label: "دماوند", value: "دماوند" },
  ],
  "چهارمحال و بختیاری": [
    { label: "شهرکرد", value: "شهرکرد" },
    { label: "بروجن", value: "بروجن" },
    { label: "فارسان", value: "فارسان" },
    { label: "لردگان", value: "لردگان" },
  ],
  "خراسان جنوبی": [
    { label: "بیرجند", value: "بیرجند" },
    { label: "قائن", value: "قائن" },
    { label: "فردوس", value: "فردوس" },
    { label: "طبس", value: "طبس" },
  ],
  "خراسان رضوی": [
    { label: "مشهد", value: "مشهد" },
    { label: "نیشابور", value: "نیشابور" },
    { label: "سبزوار", value: "سبزوار" },
    { label: "قوچان", value: "قوچان" },
    { label: "گناباد", value: "گناباد" },
    { label: "تربت حیدریه", value: "تربت حیدریه" },
    { label: "کاشمر", value: "کاشمر" },
  ],
  "خراسان شمالی": [
    { label: "بجنورد", value: "بجنورد" },
    { label: "شیروان", value: "شیروان" },
    { label: "اسفراین", value: "اسفراین" },
    { label: "جاجرم", value: "جاجرم" },
  ],
  "خوزستان": [
    { label: "اهواز", value: "اهواز" },
    { label: "آبادان", value: "آبادان" },
    { label: "خرمشهر", value: "خرمشهر" },
    { label: "دزفول", value: "دزفول" },
    { label: "اندیمشک", value: "اندیمشک" },
    { label: "شوشتر", value: "شوشتر" },
    { label: "بهبهان", value: "بهبهان" },
    { label: "ماهشهر", value: "ماهشهر" },
  ],
  "زنجان": [
    { label: "زنجان", value: "زنجان" },
    { label: "ابهر", value: "ابهر" },
    { label: "خدابنده", value: "خدابنده" },
    { label: "خرمدره", value: "خرمدره" },
  ],
  "سمنان": [
    { label: "سمنان", value: "سمنان" },
    { label: "شاهرود", value: "شاهرود" },
    { label: "دامغان", value: "دامغان" },
    { label: "گرمسار", value: "گرمسار" },
  ],
  "سیستان و بلوچستان": [
    { label: "زاهدان", value: "زاهدان" },
    { label: "زابل", value: "زابل" },
    { label: "چابهار", value: "چابهار" },
    { label: "ایرانشهر", value: "ایرانشهر" },
    { label: "سراوان", value: "سراوان" },
  ],
  "فارس": [
    { label: "شیراز", value: "شیراز" },
    { label: "مرودشت", value: "مرودشت" },
    { label: "جهرم", value: "جهرم" },
    { label: "فسا", value: "فسا" },
    { label: "کازرون", value: "کازرون" },
    { label: "لارستان", value: "لارستان" },
  ],
  "قزوین": [
    { label: "قزوین", value: "قزوین" },
    { label: "تاکستان", value: "تاکستان" },
    { label: "آبیک", value: "آبیک" },
    { label: "البرز", value: "البرز" },
  ],
  "قم": [{ label: "قم", value: "قم" }],
  "کردستان": [
    { label: "سنندج", value: "سنندج" },
    { label: "مریوان", value: "مریوان" },
    { label: "بانه", value: "بانه" },
    { label: "سقز", value: "سقز" },
    { label: "قروه", value: "قروه" },
  ],
  "کرمان": [
    { label: "کرمان", value: "کرمان" },
    { label: "سیرجان", value: "سیرجان" },
    { label: "رفسنجان", value: "رفسنجان" },
    { label: "بم", value: "بم" },
    { label: "جیرفت", value: "جیرفت" },
    { label: "زرند", value: "زرند" },
  ],
  "کرمانشاه": [
    { label: "کرمانشاه", value: "کرمانشاه" },
    { label: "اسلام آباد غرب", value: "اسلام آباد غرب" },
    { label: "سنقر", value: "سنقر" },
    { label: "پاوه", value: "پاوه" },
    { label: "کنگاور", value: "کنگاور" },
  ],
  "کهگیلویه و بویراحمد": [
    { label: "یاسوج", value: "یاسوج" },
    { label: "گچساران", value: "گچساران" },
    { label: "دوگنبدان", value: "دوگنبدان" },
  ],
  "گلستان": [
    { label: "گرگان", value: "گرگان" },
    { label: "گنبد کاووس", value: "گنبد کاووس" },
    { label: "علی آباد کتول", value: "علی آباد کتول" },
    { label: "بندر ترکمن", value: "بندر ترکمن" },
  ],
  "گیلان": [
    { label: "رشت", value: "رشت" },
    { label: "انزلی", value: "انزلی" },
    { label: "لاهیجان", value: "لاهیجان" },
    { label: "لنگرود", value: "لنگرود" },
    { label: "رودسر", value: "رودسر" },
    { label: "تالش", value: "تالش" },
  ],
  "لرستان": [
    { label: "خرم آباد", value: "خرم آباد" },
    { label: "بروجرد", value: "بروجرد" },
    { label: "دورود", value: "دورود" },
    { label: "الیگودرز", value: "الیگودرز" },
    { label: "ازنا", value: "ازنا" },
  ],
  "مازندران": [
    { label: "آمل", value: "آمل" },
    { label: "بابل", value: "بابل" },
    { label: "بابلسر", value: "بابلسر" },
    { label: "بهشهر", value: "بهشهر" },
    { label: "تنکابن", value: "تنکابن" },
    { label: "جویبار", value: "جویبار" },
    { label: "چالوس", value: "چالوس" },
    { label: "رامسر", value: "رامسر" },
    { label: "ساری", value: "ساری" },
    { label: "سوادکوه", value: "سوادکوه" },
    { label: "سوادکوه شمالی", value: "سوادکوه شمالی" },
    { label: "سیمرغ", value: "سیمرغ" },
    { label: "عباس‌آباد", value: "عباس‌آباد" },
    { label: "فریدونکنار", value: "فریدونکنار" },
    { label: "قائم‌شهر", value: "قائم‌شهر" },
    { label: "کلاردشت", value: "کلاردشت" },
    { label: "گلوگاه", value: "گلوگاه" },
    { label: "محمودآباد", value: "محمودآباد" },
    { label: "میاندورود", value: "میاندورود" },
    { label: "نکا", value: "نکا" },
    { label: "نوشهر", value: "نوشهر" },
    { label: "نور", value: "نور" },
  ],
  "مرکزی": [
    { label: "اراک", value: "اراک" },
    { label: "ساوه", value: "ساوه" },
    { label: "خمین", value: "خمین" },
    { label: "محلات", value: "محلات" },
    { label: "دلیجان", value: "دلیجان" },
  ],
  "هرمزگان": [
    { label: "بندرعباس", value: "بندرعباس" },
    { label: "قشم", value: "قشم" },
    { label: "کیش", value: "کیش" },
    { label: "میناب", value: "میناب" },
    { label: "بندر لنگه", value: "بندر لنگه" },
  ],
  "همدان": [
    { label: "همدان", value: "همدان" },
    { label: "ملایر", value: "ملایر" },
    { label: "نهاوند", value: "نهاوند" },
    { label: "تویسرکان", value: "تویسرکان" },
    { label: "اسدآباد", value: "اسدآباد" },
  ],
  "یزد": [
    { label: "یزد", value: "یزد" },
    { label: "میبد", value: "میبد" },
    { label: "اردکان", value: "اردکان" },
    { label: "تفت", value: "تفت" },
    { label: "مهریز", value: "مهریز" },
  ],
};
